//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::Serialize;
use sea_orm::{DatabaseConnection, EntityTrait, QueryFilter, ColumnTrait, DbErr};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "cassettes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: Option<String>,
    pub sprockets: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}


impl Entity {
    pub async fn get_by_id(db: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
        Self::find().filter(Column::Id.eq(id)).one(db).await
    }

    pub async fn get_all(db: &DatabaseConnection) -> Result<Vec<Model>, DbErr> {
        Self::find().all(db).await
    }
}
