name: Backend_Tests_Java

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test_java:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./back_end_java
    steps:
    - uses: actions/checkout@v6
    - name: Run Tests
      run: |
        docker run -v $(pwd)/:/app --workdir /app eclipse-temurin:25-jdk ./mvnw test
    - name: Upload code coverage results
      uses: actions/upload-artifact@v7
      with:
        name: code-coverage-report-java
        path: back_end_java/target/site/jacoco
        retention-days: 7