name: Backend_Tests_Python

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test_python:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./back_end_python
    steps:
    - uses: actions/checkout@v6
    - name: Run Tests
      run: |
        mv .env.example .env
        docker run -v $(pwd)/:/app --workdir /app python:3.14-trixie sh -c "pip3 install -r requirments.txt && pip3 install -e . && coverage run -m pytest && coverage html"
    - name: Upload code coverage results
      uses: actions/upload-artifact@v7
      with:
        name: code-coverage-report-python
        path: back_end_python/htmlcov
        retention-days: 7